### ISSUE TITLE
RPG Maker 2003 Autotiles do not work

### ISSUE THREAD

**Issue by TomCoursow** [HermesPasser/Tilecon#3]
When converting from 2003 the output results seems to use the wrong single tile picture.
In RPG Maker MV only grass Tiles are displayed in the Tile View

![image](https://user-images.githubusercontent.com/17900090/67957582-1edf7b80-fbf6-11e9-942e-a177df5c7a7c.png)

![image](https://user-images.githubusercontent.com/17900090/67957865-88f82080-fbf6-11e9-8cee-28033177bb05.png)

**Comment by TomCoursow** [comment]
Fixed bug with PullRequest #4

**Comment by HermesPasser** [comment]
Sorry for the long wait, i will look up #4
